config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'chatrooms#index'

  devise_for :users
  resources :users, only: :index
  resources :friendships, only: %i[index update create destroy]

  resources :chatrooms, only: %i[index show] do
    resources :messages, except: %i[index new]
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates :content, presence: true

  broadcasts_to ->(message) { message.chatroom }, insert_by: :prepend

  after_create_commit { broadcasts_replace_to_chatrooms_list }

  private

  def broadcasts_replace_to_chatrooms_list
    chatroom.chatrooms_users.each do |chatroom_user|
      broadcast_replace_to "chatrooms_#{chatroom_user.user.id}",
                           partial: 'chatrooms/list',
                           locals: { chatrooms: chatroom_user.user.chatrooms.ordered_by_last_message.to_a,
                                     curr_user: chatroom_user.user },
                           target: 'chatrooms'
    end
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  load_and_authorize_resource except: :create

  before_action :set_chatroom, only: :create

  def show; end

  def edit; end

  def create
    @message = @chatroom.messages.new(message_params.merge(user: current_user))

    authorize! :create, @message
    return if @message.save

    render :new, status: :unprocessable_entity
  end

  def update
    if @message.update(message_params)
      flash.now[:success] = I18n.t('flash.actions.update.success', resource_name: Message.model_name.human)
    else
      flash[:error] = I18n.t('flash.actions.update.error', resource_name: Message.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    return unless @message.destroy

    flash.now[:success] = I18n.t('flash.actions.destroy.success', resource_name: Message.model_name.human)
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/messages/_form.html.slim
= simple_form_for([message.chatroom, message], html: { class: "flex flex-col" }) do |form|
  .text-red-500.my-2
    - form.object.errors.full_messages.each do |error|
      = error
  .pb-2.px-4
    = form.textarea :content, class: "w-full border rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-600"
  .flex.justify-end
    = form.submit "Send", class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600"

app/views/messages/_message.html.slim
= turbo_frame_tag message
  .message.relative class="message-#{message.user.id}"
    .message--menu.opacity-0.pointer-events-none.absolute.right-0.top-0.flex.gap-2
      = link_to 'Edit', edit_chatroom_message_path(message.chatroom, message), class: 'text-blue-500'
      = button_to 'Delete', chatroom_message_path(message.chatroom, message), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'text-red-500'
    .message-header.flex.items-center.mb-2
      .message-author.font-bold.text-blue-600.mr-2 = message.user.email
      .message-timestamp.text-gray-500.text-sm = message.created_at.strftime("%Y-%m-%d %H:%M")
    p.message-content.border.border-green-500.bg-white.p-2.rounded-lg.shadow-md.break-all
      = message.content

app/views/messages/create.turbo_stream.slim
= turbo_stream.append 'messages', partial: 'message', collection: @chatroom.messages
= turbo_stream.update 'new-message', partial: 'form', locals: { message: @chatroom.messages.new }
= turbo_stream.replace('flashes',  partial: 'shared/flashes', locals: { flash: flash })

app/views/messages/destroy.turbo_stream.slim
= turbo_stream.remove @message
= turbo_stream.replace('flashes',  partial: 'shared/flashes', locals: { flash: flash })

app/views/messages/edit.html.slim
= turbo_frame_tag @message
  .message.relative class="message-#{@message.user.id}"
    .message--menu.opacity-0.pointer-events-none.absolute.right-0.top-0.flex.gap-2
      = link_to 'Cancel', [@message.chatroom, @message], class: 'text-blue-500'
    .message-header.flex.items-center.mb-2
      .message-author.font-bold.text-blue-600.mr-2 = @message.user.email
      .message-timestamp.text-gray-500.text-sm = @message.created_at.strftime("%Y-%m-%d %H:%M")
    .message-content.border.border-green-500.bg-white.p-2.rounded-lg.shadow-md
      = render 'form', message: @message

app/views/messages/edit.turbo_stream.slim
= turbo_stream.replace "edit_message_#{@message.id}", partial: 'form', locals: { message: @message }
= turbo_stream.replace('flashes',  partial: 'shared/flashes', locals: { flash: flash })

app/views/messages/new.html.slim
= turbo_frame_tag "new_message" do
  = render 'form', message: @message

app/views/messages/new.turbo_stream.slim
= turbo_stream.update 'new_message', partial: 'form', locals: { message: @message }
= turbo_stream.replace('flashes',  partial: 'shared/flashes', locals: { flash: flash })

app/views/messages/show.html.slim
= render 'message', message: @message

app/views/messages/update.turbo_stream.slim
= turbo_stream.update @message
= turbo_stream.replace('flashes',  partial: 'shared/flashes', locals: { flash: flash })