config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'chatrooms#index'

  devise_for :users
  resources :users, only: :index
  resources :friendships, only: %i[index update create destroy]

  resources :chatrooms, only: %i[index show] do
    resources :messages, except: %i[index new]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chatrooms_users, dependent: :destroy
  has_many :chatrooms, through: :chatrooms_users
  has_many :messages, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :pending_friendships, -> { where(status: :pending) }, class_name: 'Friendship', dependent: :destroy, inverse_of: :user
  has_many :sent_friendships, -> { where(status: :sent) }, class_name: 'Friendship', dependent: :destroy, inverse_of: :user
  has_many :confirmed_friendships, -> { where(status: :confirmed) }, class_name: 'Friendship', dependent: :destroy, inverse_of: :user
  has_many :friends, through: :friendships

  scope :by_email, ->(email) { email.present? ? where('email LIKE ?', "%#{email}%") : none }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include HasScope

  before_action :authenticate_user!

  def index
    @users = User.by_email(params[:by_email]).where.not(id: current_user.id)
  end
end

app/views/users/_list.html.slim
.mx-auto
  = simple_form_for :by_email, url: users_path, method: :get, data: { turbo_frame: :users } do |f|
    = f.input :email, label: false, placeholder: 'Search by email', input_html: { name: :by_email }

.flex.flex-col.gap-2
  - users.each do |user|
    = render user

app/views/users/_user.html.slim
= turbo_frame_tag dom_id(user)
  .border-b.border-gray-400.px-4.py-2.flex.justify-between
    = user.email
    .flex.gap-2
      - if current_user.friends.include?(user)
        - friendship = current_user.friendships.find_by(friend_id: user.id)
        - if friendship.confirmed?
          = button_to 'Send message', chatrooms_path(chatroom: { user_ids: [user.id] }), data: { turbo_frame: '_top' }, class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700"
          = link_to 'Unfriend',friendship_path(friendship), data: { turbo_method: :delete }, class: "bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700"
        - elsif friendship.sent?
          = link_to 'Unfriend',friendship_path(friendship), data: { turbo_method: :delete }, class: "bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700"
        - else
          = link_to 'Accept', friendship_path(friendship), data: { turbo_method: :patch }, class: "bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700"
          = link_to 'Decline', friendship_path(friendship), data: { turbo_method: :delete }, class: "bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700"
      - else
        = button_to 'Invite', friendships_path(friend_id: user.id), method: :post , class: "bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700"

app/views/users/index.html.slim
= turbo_frame_tag 'users'
  = render 'list', users: @users

app/views/users/show.html.slim
h1 = @user.email
p
  | Email: 
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|  |
= link_to 'Back', users_path